import React from "react";

export default async function Head() {
  return (
    <>
        <title>Hempire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </>
  );
}
