import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero';
 
export default function Home() {
  return (
    <div>
      <Head>
        <title>Hempire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Hempire' message='A rock and roll band based out of Boone, NC.'/>
    </div>
  )
}
