import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero';
import Instagram from '../components/Instagram'
import Instagram_Img from '../components/Instagram_Img';
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'
 
export default function Home() {
  return (
    <div>
      <Head>
        <title>Hempire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-primary'>
      <Hero message='A rock and roll band based out of Boone, NC.' button='Gallery'/>
      <Slider slides={SliderData} />
      <Instagram />
      </div>
    </div>
  )
}
